module.exports = {
  USER_CREATED: 'USER_CREATED',

  SONG_CREATED: 'SONG_CREATED',
  SONG_CONSOLIDATED: 'SONG_CONSOLIDATED',
  SONG_UPDATED: 'SONG_UPDATED',

  // initial songs added for a user's station:
  STATION_SONGS_INITIALIZED: 'STATION_SONGS_INITIALIZED',
};
